/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FitnessGoal = IDL.Variant({
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintenance' : IDL.Null,
  'endurance' : IDL.Null,
});
export const UserStats = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'activityLevel' : IDL.Opt(IDL.Text),
  'heightCm' : IDL.Opt(IDL.Float64),
  'weightKg' : IDL.Opt(IDL.Float64),
});
export const MacroSplit = IDL.Record({
  'calories' : IDL.Float64,
  'fatsGrams' : IDL.Float64,
  'carbsGrams' : IDL.Float64,
  'proteinGrams' : IDL.Float64,
});
export const MealSuggestion = IDL.Record({
  'carbs' : IDL.Float64,
  'fats' : IDL.Float64,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'protein' : IDL.Float64,
});
export const DietPlan = IDL.Record({
  'recommendedMacros' : MacroSplit,
  'goal' : FitnessGoal,
  'guidelines' : IDL.Text,
  'mealSuggestions' : IDL.Vec(MealSuggestion),
});
export const WeeklySchedule = IDL.Record({
  'sessionLengthMinutes' : IDL.Nat,
  'totalSessions' : IDL.Nat,
  'restDays' : IDL.Vec(IDL.Text),
  'daysPerWeek' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'caloriesPerSet' : IDL.Opt(IDL.Nat),
  'caloriesPerMinute' : IDL.Opt(IDL.Nat),
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'reps' : IDL.Opt(IDL.Nat),
  'sets' : IDL.Opt(IDL.Nat),
  'durationMinutes' : IDL.Opt(IDL.Nat),
});
export const WorkoutPlan = IDL.Record({
  'weeklySchedule' : WeeklySchedule,
  'goal' : FitnessGoal,
  'exerciseList' : IDL.Vec(Exercise),
  'estimatedCaloriesPerSession' : IDL.Nat,
  'planType' : IDL.Text,
});
export const Time = IDL.Int;
export const CalorieBurnActivity = IDL.Record({
  'activityName' : IDL.Text,
  'difficulty' : Difficulty,
  'durationMinutes' : IDL.Nat,
  'timestamp' : Time,
  'caloriesBurned' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, Difficulty], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generatePersonalizedDietPlan' : IDL.Func(
      [FitnessGoal, IDL.Opt(UserStats)],
      [DietPlan],
      ['query'],
    ),
  'generateWorkoutPlan' : IDL.Func([FitnessGoal], [WorkoutPlan], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(CalorieBurnActivity)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyCalorieGoal' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserActivities' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CalorieBurnActivity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyCalorieGoal' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FitnessGoal = IDL.Variant({
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintenance' : IDL.Null,
    'endurance' : IDL.Null,
  });
  const UserStats = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'activityLevel' : IDL.Opt(IDL.Text),
    'heightCm' : IDL.Opt(IDL.Float64),
    'weightKg' : IDL.Opt(IDL.Float64),
  });
  const MacroSplit = IDL.Record({
    'calories' : IDL.Float64,
    'fatsGrams' : IDL.Float64,
    'carbsGrams' : IDL.Float64,
    'proteinGrams' : IDL.Float64,
  });
  const MealSuggestion = IDL.Record({
    'carbs' : IDL.Float64,
    'fats' : IDL.Float64,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const DietPlan = IDL.Record({
    'recommendedMacros' : MacroSplit,
    'goal' : FitnessGoal,
    'guidelines' : IDL.Text,
    'mealSuggestions' : IDL.Vec(MealSuggestion),
  });
  const WeeklySchedule = IDL.Record({
    'sessionLengthMinutes' : IDL.Nat,
    'totalSessions' : IDL.Nat,
    'restDays' : IDL.Vec(IDL.Text),
    'daysPerWeek' : IDL.Nat,
  });
  const Exercise = IDL.Record({
    'caloriesPerSet' : IDL.Opt(IDL.Nat),
    'caloriesPerMinute' : IDL.Opt(IDL.Nat),
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'reps' : IDL.Opt(IDL.Nat),
    'sets' : IDL.Opt(IDL.Nat),
    'durationMinutes' : IDL.Opt(IDL.Nat),
  });
  const WorkoutPlan = IDL.Record({
    'weeklySchedule' : WeeklySchedule,
    'goal' : FitnessGoal,
    'exerciseList' : IDL.Vec(Exercise),
    'estimatedCaloriesPerSession' : IDL.Nat,
    'planType' : IDL.Text,
  });
  const Time = IDL.Int;
  const CalorieBurnActivity = IDL.Record({
    'activityName' : IDL.Text,
    'difficulty' : Difficulty,
    'durationMinutes' : IDL.Nat,
    'timestamp' : Time,
    'caloriesBurned' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, Difficulty], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generatePersonalizedDietPlan' : IDL.Func(
        [FitnessGoal, IDL.Opt(UserStats)],
        [DietPlan],
        ['query'],
      ),
    'generateWorkoutPlan' : IDL.Func([FitnessGoal], [WorkoutPlan], ['query']),
    'getAllActivities' : IDL.Func(
        [],
        [IDL.Vec(CalorieBurnActivity)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyCalorieGoal' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserActivities' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CalorieBurnActivity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyCalorieGoal' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };