/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalorieBurnActivity {
  'activityName' : string,
  'difficulty' : Difficulty,
  'durationMinutes' : bigint,
  'timestamp' : Time,
  'caloriesBurned' : bigint,
}
export interface DietPlan {
  'recommendedMacros' : MacroSplit,
  'goal' : FitnessGoal,
  'guidelines' : string,
  'mealSuggestions' : Array<MealSuggestion>,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Exercise {
  'caloriesPerSet' : [] | [bigint],
  'caloriesPerMinute' : [] | [bigint],
  'difficulty' : Difficulty,
  'name' : string,
  'reps' : [] | [bigint],
  'sets' : [] | [bigint],
  'durationMinutes' : [] | [bigint],
}
export type FitnessGoal = { 'weightLoss' : null } |
  { 'muscleGain' : null } |
  { 'maintenance' : null } |
  { 'endurance' : null };
export interface MacroSplit {
  'calories' : number,
  'fatsGrams' : number,
  'carbsGrams' : number,
  'proteinGrams' : number,
}
export interface MealSuggestion {
  'carbs' : number,
  'fats' : number,
  'calories' : number,
  'name' : string,
  'description' : string,
  'protein' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'age' : [] | [bigint],
  'activityLevel' : [] | [string],
  'heightCm' : [] | [number],
  'weightKg' : [] | [number],
}
export interface WeeklySchedule {
  'sessionLengthMinutes' : bigint,
  'totalSessions' : bigint,
  'restDays' : Array<string>,
  'daysPerWeek' : bigint,
}
export interface WorkoutPlan {
  'weeklySchedule' : WeeklySchedule,
  'goal' : FitnessGoal,
  'exerciseList' : Array<Exercise>,
  'estimatedCaloriesPerSession' : bigint,
  'planType' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivity' : ActorMethod<[string, bigint, bigint, Difficulty], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generatePersonalizedDietPlan' : ActorMethod<
    [FitnessGoal, [] | [UserStats]],
    DietPlan
  >,
  'generateWorkoutPlan' : ActorMethod<[FitnessGoal], WorkoutPlan>,
  'getAllActivities' : ActorMethod<[], Array<CalorieBurnActivity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyCalorieGoal' : ActorMethod<[], bigint>,
  'getUserActivities' : ActorMethod<[Principal], Array<CalorieBurnActivity>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDailyCalorieGoal' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];